name: OUR .ecmp file check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test packages
      run: docker run ghcr.io/soviet-linux/cccp spm-test install testing/src/*.ecmp && docker run ghcr.io/soviet-linux/cccp spm-test install lxde/src/*.ecmp && docker run ghcr.io/soviet-linux/cccp spm-test install xorg/src/*.ecmp && spm-test install xfce/src/*.ecmp && docker run ghcr.io/soviet-linux/cccp spm-test install kde/src/*.ecmp && docker run ghcr.io/soviet-linux/cccp spm-test install base/src/*.ecmp
