name: OUR .ecmp file check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get container
      run: docker pull ghcr.io/soviet-linux/cccp:sha256-b57f307e4817a525a76ae581bc0220f97073d19806c4ddf8649eaae3df1b956d.sig
    - name: Test packages
      run: docker run cccp spm-test install testing/src/*.ecmp && docker run cccp spm-test install lxde/src/*.ecmp && docker run cccp spm-test install xorg/src/*.ecmp && spm-test install xfce/src/*.ecmp && docker run cccp spm-test install kde/src/*.ecmp && docker run cccp spm-test install base/src/*.ecmp
